-- MySQL Script generated by MySQL Workbench
-- Tue Oct 20 13:49:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DelilahFV
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DelilahFV
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DelilahFV` DEFAULT CHARACTER SET utf8 ;
USE `DelilahFV` ;

-- -----------------------------------------------------
-- Table `DelilahFV`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DelilahFV`.`Cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(20) NOT NULL,
  `Password` VARCHAR(100) NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(20) NOT NULL,
  `Direccion` VARCHAR(400) NOT NULL,
  `tipoUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DelilahFV`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DelilahFV`.`Productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Descripcion` VARCHAR(2000) NULL,
  `Precio` FLOAT NOT NULL,
  `Stock` INT NOT NULL,
  PRIMARY KEY (`idProductos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DelilahFV`.`Estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DelilahFV`.`Estados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `EstadoDelPedido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DelilahFV`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DelilahFV`.`Pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Fecha` VARCHAR(50) NOT NULL,
  `PrecioTotal` FLOAT NULL,
  `Estados_id` INT NOT NULL,
  `FormaDePago` INT NOT NULL,
  `Cliente_id` INT NOT NULL,
  INDEX `fk_Pedidos_Estados1_idx` (`Estados_id` ASC),
  INDEX `fk_Pedidos_Cliente1_idx1` (`Cliente_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Pedidos_Estados1`
    FOREIGN KEY (`Estados_id`)
    REFERENCES `DelilahFV`.`Estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Cliente1`
    FOREIGN KEY (`Cliente_id`)
    REFERENCES `DelilahFV`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DelilahFV`.`Pedidos_Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DelilahFV`.`Pedidos_Productos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `CantidadProduct` INT NULL,
  `Precio` FLOAT NULL,
  `Productos_idProductos` INT NOT NULL,
  `Compra` VARCHAR(100) NULL,
  `Cliente_id` INT NOT NULL,
  PRIMARY KEY (`Id`, `Compra`),
  INDEX `fk_Pedidos_Productos_Productos1_idx` (`Productos_idProductos` ASC),
  INDEX `fk_Pedidos_Productos_Cliente1_idx` (`Cliente_id` ASC),
  CONSTRAINT `fk_Pedidos_Productos_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `DelilahFV`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Productos_Cliente1`
    FOREIGN KEY (`Cliente_id`)
    REFERENCES `DelilahFV`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DelilahFV`.`Favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DelilahFV`.`Favoritos` (
  `Productos_idProductos` INT NOT NULL,
  `Cliente_id` INT NOT NULL,
  INDEX `fk_Favoritos_Productos1_idx` (`Productos_idProductos` ASC),
  INDEX `fk_Favoritos_Cliente1_idx` (`Cliente_id` ASC),
  CONSTRAINT `fk_Favoritos_Productos1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `DelilahFV`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favoritos_Cliente1`
    FOREIGN KEY (`Cliente_id`)
    REFERENCES `DelilahFV`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
